// https://nuxt.com/docs/api/configuration/nuxt-config
import { join, sep } from "path";
import { globSync } from "glob";
import { pathExists, copy } from "fs-extra";
import type { LocaleObject, Directions } from "@nuxtjs/i18n";

// Locale codes enabled in the app (keep in sync with the `locales` array and
// the per-page custom route slugs below). `pt` is currently disabled.
type AppLocale = "ar" | "de" | "en" | "es" | "fr" | "he" | "jp" | "ru" | "zh";

// List of supported languages
const localeDefinitions: LocaleObject<AppLocale>[] = [
  {
    code: "en",
    language: "en-US",
    name: "English",
    file: "en.json",
  },
  {
    code: "fr",
    name: "Français",
    language: "fr-FR",
    file: "fr.json",
  },
  {
    code: "de",
    name: "Deutsch",
    language: "de-DE",
    file: "de.json",
  },
  {
    code: "ru",
    name: "Русский",
    language: "ru-RU",
    file: "ru.json",
  },
  {
    code: "he",
    name: "עִברִית",
    language: "he-IL",
    file: "he.json",
    dir: "rtl" as Directions,
  },
  {
    code: "ar",
    name: "العربية الفصحى",
    language: "ar-001",
    file: "ar.json",
    dir: "rtl" as Directions,
  },
  {
    code: "es",
    name: "Español",
    language: "es-ES",
    file: "es.json",
  },
  /*
  {
    code: "pt",
    name: "Português",
    language: "pt-PT",
    file: "pt.json",
  },
  */
  {
    code: "zh",
    name: "中文（繁體）",
    language: "zh-CN",
    file: "zh.json",
  },
  {
    code: "jp",
    name: "日本語",
    language: "ja-JP",
    file: "jp.json",
  },
];

const locales = localeDefinitions.sort((a, b) => a.code.localeCompare(b.code));

const publicWebUrl = process.env.PUBLIC_WEB_URL || "https://beam.mw";

// https://github.com/nuxt/content/issues/1551#issuecomment-1470246543
// Added README to index replacement (as understood by the slug)
const contentRoutes = globSync("./content/**/*.md")
  .map((path) => {
    if (path.startsWith("./content/docs/")) {
      return path
        .slice(7, -3)
        .replace(/^\d+\./, "")
        .replace(/\\/g, "/")
        .replace("/README", "/index");
    }
    if (path.startsWith("./content/blog/")) {
      return path.slice(7, -3).replace(/\\/g, "/");
    }
    return null;
  })
  .filter(Boolean) as string[];

const copyDocsAssetsToPublic = async () => {
  const docsPath = join(process.cwd(), "content", "docs");
  const publicAssetsPath = join(process.cwd(), "public", "assets", "docs");

  // Find all .gitbook/assets folders within the subdirectories of 'content/docs'
  const gitbookAssetsFolders = globSync("**/.gitbook/assets", {
    cwd: docsPath,
  });

  // Iterate over the .gitbook/assets folders and copy their contents
  for (const gitbookAssetsFolder of gitbookAssetsFolders) {
    const source = join(docsPath, gitbookAssetsFolder);
    // Get the parent directory name without the '.gitbook/assets' part
    const destinationFolder = gitbookAssetsFolder.replace(
      `${sep}.gitbook${sep}assets`,
      "",
    );
    const destination = join(publicAssetsPath, destinationFolder);

    // Check if the destination folder exists
    const folderExists = await pathExists(destination);

    // If the destination folder doesn't exist, copy the contents of the .gitbook/assets folder to the destination folder
    if (!folderExists) {
      await copy(source, destination);
      // eslint-disable-next-line no-console
      console.log(`Contents of ${source} copied to ${destination}.`);
    }
  }
};

export default defineNuxtConfig({
  ssr: true,
  // pageTransition and layoutTransition both default to false in Nuxt 3,
  // so no explicit `app` transition config is needed while they stay disabled.
  experimental: {
    viewTransition: true,
  },
  modules: [
    "@nuxtjs/tailwindcss",
    "@nuxtjs/i18n",
    "@nuxtjs/device",
    "@nuxtjs/sitemap",
    "@nuxtjs/robots",
    "nuxt-seo-utils",
    "nuxt-security",
    "@nuxtjs/fontaine",
    "@nuxt/content",
  ],
  security: {
    nonce: true,
    ssg: {
      hashScripts: true, // In the SSG case, inline scripts generated by the server will be allowed by hash
    },
    rateLimiter: false,
    sri: true,
    headers: {
      contentSecurityPolicy: {
        "connect-src": `'self' https://api.coingecko.com https://dex.beam.mw https://builds.beam.mw${process.env.NODE_ENV === "development" ? " ws://localhost:4000" : ""}`,
        "script-src": [
          "'nonce-{{nonce}}'", // Nonce placeholders in the SSR case will allow inline scripts generated on the server
          // "'strict-dynamic'", // Use strict dynamic as outlined here: https://nuxt-security.vercel.app/documentation/advanced/strict-csp#strict-dynamic-csp-level-3
          "'self'", // Allow external scripts from self origin
          // No 'wasm-unsafe-eval': every @nuxt/content query is payload-served
          // (all queryCollection calls run inside useAsyncData, and no page wraps
          // its content component in <RenderCacheable>), so the client-side
          // SQLite-WASM engine is never instantiated in the browser. Keep it that
          // way — a client-only query (e.g. a live useSearchCollection) would
          // reintroduce the WASM boot and require this directive again.
        ],
        "worker-src": "'self'",
        "frame-ancestors": false, // This one doesn't work when CSP is in Meta
      },
    },
    removeLoggers: {
      external: [],
      consoleType: ["log", "debug"],
      include: [/\.[jt]sx?$/, /\.vue\??/],
      exclude: [/node_modules/, /\.git/],
    },
  },
  nitro: {
    prerender: {
      routes: [...contentRoutes],
      crawlLinks: true,
      failOnError: false,
      // Emit flat "foo.html" files instead of "foo/index.html". Cloudflare
      // Pages then treats the no-trailing-slash URL as canonical (and 301s
      // "/foo/" -> "/foo" at the edge), instead of canonicalizing to the
      // trailing-slash form. That keeps the canonical URL aligned with the
      // sitemap and the trailing-slash middleware — no redirect churn.
      autoSubfolderIndex: false,
    },
  },
  hooks: {
    "build:before": async () => {
      await copyDocsAssetsToPublic();
    },
  },
  runtimeConfig: {
    public: {
      siteUrl: publicWebUrl,
      baseURL: publicWebUrl,
    },
  },
  content: {
    // Collections, sources and per-collection schema are defined in
    // content.config.ts (Content v3). Global build options live here.
    build: {
      markdown: {
        remarkPlugins: { "remark-gfm": {} },
        highlight: { theme: "github-dark" },
      },
    },
  },
  site: {
    siteUrl: publicWebUrl,
  },
  sitemap: {
    discoverImages: false,
    autoLastmod: true,
    credits: false,
  },
  typescript: {
    typeCheck: true,
    strict: true,
  },
  fontMetrics: {
    // Paths are resolved relative to the public dir by @nuxtjs/fontaine, so
    // they must not start with a leading slash (which would be treated as an
    // absolute filesystem path).
    fonts: [
      { family: "ProximaNova", src: "fonts/ProximaNova-Regular.woff2" },
      {
        family: "ProximaNova-Italic",
        src: "fonts/ProximaNova-RegularIt.woff2",
      },
      { family: "ProximaNova-Bold", src: "fonts/ProximaNova-Bold.woff2" },
    ],
  },
  i18n: {
    baseUrl: publicWebUrl,
    skipSettingLocaleOnNavigate: false,
    defaultLocale: "en",
    langDir: "locales",
    vueI18n: "./i18n.config.ts",
    customRoutes: "config", // Disable custom route with page components
    strategy: "prefix_and_default",
    pages: {
      downloads: {
        en: "/downloads",
        fr: "/telechargements",
        zh: "/下载",
        jp: "/ダウンロード",
        de: "/downloads",
        ru: "/загрузки",
        he: "/הורדות",
        ar: "/تنزيلات",
        es: "/descargas",
      },
      "privacy-policy": {
        en: "/privacy-policy",
        fr: "/politique-de-confidentialite",
        zh: "/隐私政策",
        jp: "/プライバシーポリシー",
        de: "/datenschutzrichtlinie",
        ru: "/политикаконфиденциальности",
        he: "/מדיניותפרטיות",
        ar: "/سياسةالخصوصية",
        es: "/politica-de-privacidad",
      },
      mining: {
        en: "/mining",
        fr: "/minage",
        zh: "/挖矿",
        jp: "/マイニング",
        de: "/mining",
        ru: "/майнинг",
        he: "/כרייה",
        ar: "/تعدين",
        es: "/mineria",
      },
    },
    locales,
  },
});
