# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: "Deploy to CloudFlare"

on: [push, pull_request]

env:
  NODE_OPTIONS: --max-old-space-size=7620
  NODE_VERSION: 20.10.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      PUBLIC_WEB_URL: ${{ secrets.PUBLIC_WEB_URL }}
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Submodule update
        shell: bash
        run: git submodule update --init --recursive

      - name: Update module
        shell: bash
        run: git submodule sync && git submodule update --remote --force

      - name: Enable Corepack
        shell: bash
        run: corepack enable

      - name: Install packages
        run: yarn install

      - name: Build
        run: yarn build

      - name: Generate static
        run: yarn generate

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.PROJECT_NAME }}
          directory: "./dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
